# Generated by Django 5.0.3 on 2024-03-11 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_poll', to='polls.poll'),
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together={('poll_question', 'published_at')},
        ),
    ]
