# Generated by Django 5.0.3 on 2024-03-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choice_text',)},
        ),
    ]
