# Generated by Django 5.0.3 on 2024-03-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_question',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
