# Generated by Django 5.0.3 on 2024-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_poll_voters_count_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_question',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
