# Generated by Django 5.0.3 on 2024-03-27 03:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_poll_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_question',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
