# Generated by Django 5.0.3 on 2024-03-27 04:45

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_poll_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_descript',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_question',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
